create table account
(
    id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar(255),
    email varchar(255)
);

create table cinema_hall
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row        int,
    col        int,
    unique (row, col),
    account_id int4 references account (id),
    price float
);

insert into cinema_hall (row, col, price)
values (1, 1, 500),
       (1, 2, 500),
       (1, 3, 500),
       (2, 1, 500),
       (2, 2, 500),
       (2, 3, 500),
       (3, 1, 500),
       (3, 2, 500),
       (3, 3, 500);

insert into account
(name, email) values ('Artem', 'arkas@gmail.com')